// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5IBefwUBQ-Pj-03-1mKWkvVoEOepnh94',
    appId: '1:60767637573:web:fd830d02b8e5ff8773932c',
    messagingSenderId: '60767637573',
    projectId: 'ulearning-app-42274',
    authDomain: 'ulearning-app-42274.firebaseapp.com',
    storageBucket: 'ulearning-app-42274.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwfQPj1RbFA5JOnfYF74_n8V_lC7DRIZg',
    appId: '1:60767637573:android:1752635e1217d37d73932c',
    messagingSenderId: '60767637573',
    projectId: 'ulearning-app-42274',
    storageBucket: 'ulearning-app-42274.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdXLVy2yBgO6SadVDQbKGPs7kT2WPCHe0',
    appId: '1:60767637573:ios:87e6bed2a1619b5b73932c',
    messagingSenderId: '60767637573',
    projectId: 'ulearning-app-42274',
    storageBucket: 'ulearning-app-42274.appspot.com',
    iosClientId: '60767637573-onvu0nd10bpef7cqv7avosnqshdvmu5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.ulearningApp',
  );
}
